config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"
  devise_for :users
  root to: 'pages#home'
  get "/team" => "pages#team"
  get "/contact" => "pages#join_us"

  resources :actualites
  resources :upvotes, only: [ :create, :destroy ]

end

app/models/actualite.rb
class Actualite < ActiveRecord::Base
  has_attachment :photo

  belongs_to :user
  has_many :upvotes

  validates :name, presence: true, uniqueness: false
  validates :tagline, presence: true, uniqueness: false
  validates :classification, inclusion: { in: %w(cinema debat musique),
    message: "%{value} is not a valid classification" }
end

app/models/upvote.rb
class Upvote < ActiveRecord::Base
  belongs_to :user
  belongs_to :actualite

  validates :user, uniqueness: { scope: :actualite }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :actualites
  has_many :upvotes
  has_attachment :avatar
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def voted_for?(actualite)
    actualite.upvotes.where(user: self).any?
  end
end

app/controllers/actualites_controller.rb
class ActualitesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]
  before_action :find_product, only: [:show, :edit, :update, :destroy]


  before_action :current_user?, only: [:edit, :destroy]

  def current_user?
    if @actualite.user != current_user
        flash[:alert] = "Vous n'avez pas accès à cette page."
        redirect_to actualites_path
    end
  end

  def index
    if params[:classification]
      @actualites = Actualite.where(classification: params[:classification]).order('id DESC').limit('5')
    else
      @actualites = Actualite.all.order('id DESC').limit('5')
    end
  end
  def show
    @actualite = Actualite.find(params[:id])
  end
  def new
    @actualite = Actualite.new
  end
  def create
    @actualite = Actualite.new(actualite_params)
    @actualite.user = current_user
    if @actualite.save
    redirect_to actualites_path
    else
      render :new
    end
  end
  def edit
    @actualite = Actualite.find(params[:id])
  end
  def update
    @actualite = Actualite.find(params[:id])
    if @actualite.update(actualite_params)
      redirect_to actualites_path
    else
      render :edit
    end
  end
  def destroy
    @actualite = Actualite.find(params[:id])
    @actualite.destroy
    redirect_to actualites_path
  end

  private

  def actualite_params
    params.require(:actualite).permit(:name, :tagline, :url, :classification, :calendrier, :photo)
  end
  def find_product
    @actualite = Actualite.find(params[:id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # devise_parameter_sanitizer.permit(:sign_up,        keys: [:avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:avatar])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!
  def home
    @actualites = Actualite.order('id DESC').limit('3')
  end
  def team
    @members = ["Bob", "Romain", "Seb"]
  end
  def join_us
  end
end

app/controllers/upvotes_controller.rb
class UpvotesController < ApplicationController
  def create
    actualite = Actualite.find(params[:actualite_id])
    actualite.upvotes.create! user: current_user
    redirect_to actualites_path
  end

  def destroy
    upvote = Upvote.find(params[:id])
    upvote.destroy
    redirect_to actualites_path
  end
end

app/helpers/actualites_helper.rb
module ActualitesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/upvotes_helper.rb
module UpvotesHelper
end

app/views/actualites/_form.html.erb
<%= simple_form_for @actualite do |f| %>
  <%= f.input :name, placeholder: "programmation", label: "Quelle prog ?" %>

  <%= f.input :tagline, placeholder: "Descr...", label: "Quel desc ?" %>

  <%= f.input :url, placeholder: "http://google.com", label: "Quel url ?" %>

  <%= f.input :classification, collection: ["cinema", "debat", "musique"], prompt: "wich category ?" %>

  <%= f.input :calendrier, placeholder: "Which date ?", label: "Quelle date ?" %>

  <%= f.input :photo, as: :attachinary %>

  <%= f.button :submit, "Ajouter", class: "btn btn-primary" %>
  <p class="padded"></p>
<% end %>

app/views/actualites/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1 class="text-center">Modifier une programmation à l'agenda du café (new.html.erb)</h1>

      <%= render "form" %>

    </div>
  </div>
</div>

app/views/actualites/index.html.erb
<div class="container taillecont">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <h1 class="text-center">Agenda</h1>

      <% @actualites.each do |actualite| %>

      <div class="product">
        <% if user_signed_in? %>

          <%# Upvote action %>
          <% if current_user.voted_for?(actualite) %>
            <%= link_to upvote_path(current_user.upvotes.where(actualite: actualite).first), method: :delete, class: 'product-upvote product-upvoted' do %>
              <div class="product-arrow"></div>
              <div class='product-count'>
                <%= actualite.upvotes.size %>
              </div>
            <% end %>
          <% else %>
            <%= link_to upvotes_path(actualite_id: actualite.id), method: :post, class: 'product-upvote' do %>
              <div class="product-arrow"></div>
              <div class='product-count'>
                <%= actualite.upvotes.size %>
              </div>
            <% end %>
          <% end %>

        <% else %>
          <div class='product-upvote'>
            <div class="product-arrow"></div>
            <div class='product-count'>
              <%= actualite.upvotes.size %>
            </div>
          </div>
        <% end %>


        <% if actualite.photo? %>
          <%= cl_image_tag(actualite.photo.path, height: 117, width: 175, crop: :fill, class: 'product-image') %>
        <% else %>
          <img src="http://unsplash.it/300/200" alt="kudoz" class="product-image hidden-xs">
          <% end %>

        <div class='product-body'>
          <h3><%= actualite.name %></h3>
          <p><%= actualite.tagline %></p>
        </div>
        <ul class="list-inline product-controls">
        <li>
          <%= link_to actualite_path(actualite) do %>
          <i class="fa fa-eye"></i>
          <% end %>
        </li>
        <li>
          <%= link_to edit_actualite_path(actualite) do %>
          <i class="fa fa-pencil"></i>
          <% end %>
        </li>
        <li>
          <%= link_to actualite_path(actualite), method: :delete do %>
          <i class="fa fa-trash"></i>
          <% end %>
        </li>
        </ul>
      </div>


      <% end %>

    </div>
  </div>
</div>

app/views/actualites/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1 class="text-center">Ajouter une programmation à l'agenda du café (new.html.erb)</h1>

      <%= render "form" %>

    </div>
  </div>
</div>

app/views/actualites/show.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= @actualite.photo? ? cloudinary_url(@actualite.photo.path, width: 1280, height: 700, crop: :fill) : image_path("ps.jpg") %>');">
  <div class="banner-content">
    <h1><%= @actualite.name %></h1>
    <% if @actualite.user %>
      <p>
        Posted by <%= @actualite.user.email %>
      </p>
    <% end %>
    <p class="aligng"><%= @actualite.tagline %></p>

      <table class="aligntab">
        <tr>
          <td>Catégorie</td>
          <td><%= @actualite.classification %></td>
        </tr>
        <tr>
          <td>Date</td>
          <td><%= @actualite.calendrier&&@actualite.calendrier.strftime("Le %d/%m/%Y à %H:%M") %></td>
        </tr>
        <tr>
          <% if @actualite.url %>
          <td>Site</td>
          <td><%= link_to @actualite.url, @actualite.url, class: "label label-default" %></td>
          <% end %>
        </tr>
      </table>
<!--       <div class="container">
        <div class="row">
          <div class="col-xs-12 col-sm-6 col-sm-offset-3">

          <strong><dl class="dl-horizontal" style="padding-bottom:50px";>
            <dt><i class="fa fa-phone"></i></dt>
            <dd><span class="tex">+33 (0) 6 86 59 78 51 </span></dd>
           <dt><i class="fa fa-envelope-o"></i></dt>
           <dd><span class="tex">contact [arobase] lartgrafik.com</span></dd>
           <dt><i class="fa fa-building-o"></i></dt>
           <dd><span class="tex">05000 GAP</span></dd>
          </dl></strong>

          </div>
        </div>
      </div> -->






  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Le Petit Saloon</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>

    <%= yield %>
    <%= render "shared/footer" %>

    <%= javascript_include_tag 'application' %>
    <%= cloudinary_js_config %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= image_path "ps.jpg" %>');">
  <div class="banner-content">
    <h1>THE TABLE</h1>
    <p class="accroche">Un café associatif où les adhérents se mettent à table !!</p>
    <p class="prochainement">La prog !!</p>
    <ul class="ranger">
      <% @actualites.each do |actualite| %>
      <li>
        <span class="twolastprod"><%= link_to actualite.calendrier&&actualite.calendrier.strftime("Le %d/%m/%Y à %H:%M"), actualite_path(actualite) %> - <%= link_to actualite.name, actualite_path(actualite) %></span>
      </li>
      <% end %>
    </ul>
    <%= link_to "Voir l'agenda complet", actualites_path, class: "all-agenda-button btn" %>


  </div>
</div>

<div class="container padded">
  <div class="row">
    <div class="class col-xs-12 col-sm-4">
      <%= link_to "Musique", actualites_path(classification: "musique"), class: "card-category mus" %>
    </div>
    <div class="class col-xs-12 col-sm-4">
      <%= link_to "Projections", actualites_path(classification: "cinema"), class: "card-category proj" %>
    </div>
    <div class="class col-xs-12 col-sm-4">
      <%= link_to "Débats", actualites_path(classification: "debat"), class: "card-category deb" %>
    </div>
  </div>
</div>


<div id="map" style="width: 100%; height: 400px;"></div>

<script type="text/javascript" src="http://maps.google.com/maps/api/js?key=AIzaSyAzWcEbYakX7wdJDyADFGuT0CW1bKNerF8&amp;exp&amp;sensor=false&amp;libraries=places"></script>
<script type="text/javascript">
var myLatlng = new google.maps.LatLng(44.557800, 6.076191);

var myOptions = {
  zoom: 16,
  center: myLatlng,
  scrollwheel: false,
  mapTypeId: google.maps.MapTypeId.ROADMAP,
  styles: [{"featureType":"landscape","stylers":[{"saturation":-100},{"lightness":65},{"visibility":"on"}]},{"featureType":"poi","stylers":[{"saturation":-100},{"lightness":51},{"visibility":"simplified"}]},{"featureType":"road.highway","stylers":[{"saturation":-100},{"visibility":"simplified"}]},{"featureType":"road.arterial","stylers":[{"saturation":-100},{"lightness":30},{"visibility":"on"}]},{"featureType":"road.local","stylers":[{"saturation":-100},{"lightness":40},{"visibility":"on"}]},{"featureType":"transit","stylers":[{"saturation":-100},{"visibility":"simplified"}]},{"featureType":"administrative.province","stylers":[{"visibility":"off"}]},{"featureType":"water","elementType":"labels","stylers":[{"visibility":"on"},{"lightness":-25},{"saturation":-100}]},{"featureType":"water","elementType":"geometry","stylers":[{"hue":"#ffff00"},{"lightness":-25},{"saturation":-97}]}]
};

var map = new google.maps.Map(document.getElementById('map'), myOptions);
var marker = new google.maps.Marker({
  position: myLatlng,
  map: map,
  title:"Lartgrafik"
});
</script>

app/views/pages/join_us.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= image_path "ps.jpg" %>');">
  <div class="banner-content">
    <h1>CONTACT</h1>
    <p class="accroche">Send us a mail ! !!</p>

    <%= link_to "BACK", root_path, class: "all-agenda-button btn" %>


  </div>
</div>

app/views/pages/team.html.erb
<div class="container text-center">
  <h1>Meet the team</h1>

<%= cl_image_tag "ljr7nrwxp46g6ppm829u", width: 400, height:100, crop: :fill %>

  <ul>
    <% @members.each do |onebyone| %>
      <li><%= onebyone %></li>
    <% end %>
  </ul>
</div>

app/views/shared/_flashes.html.erb
<!-- This file is in `app/views/shared/_flashes.html.erb` -->

<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
<div class="container">
  <div class="row">
    <div class="col-sm-10 col-sm-offset-1">

<p class="text-right posf">The Table 2015-2016</p><br>

    </div>
  </div>
</div>

</footer>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->

  <div class="navbar-wagon-left">

    <a href="/" class="navbar-wagon-brand">
      <%= image_tag "thetable.png" %>
    </a>

    <div class="navbar-wagon-pos hidden-xs hidden-sm">
      <%= link_to "Agenda", actualites_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Team", team_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Contact", contact_path, class: "navbar-wagon-item navbar-wagon-link" %>
    </div>
  </div>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Text link -->


    <% if user_signed_in? %>

    <!-- Profile picture and dropdown -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <% if current_user.avatar? %>
          <%= cl_image_tag current_user.avatar.path, width: 60, height: 60, crop: :fill, class: 'avatar dropdown-toggle', id: 'navbar-wagon-menu', :'data-toggle' => 'dropdown' %>
        <% else %>
          <img src="http://placehold.it/50x50" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
        <% end %>

        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Profile</a></li>
          <li><a href="#">Dashboard</a></li>
          <li><%= link_to "Profil", edit_user_registration_path %></li>
          <li>
            <%= link_to "Déconnexion", destroy_user_session_path, method: :delete %>
          </li>
        </ul>
      </div>
    </div>

    <!-- Button (call-to-action) -->
    <%= link_to "Ajouter un article", new_actualite_path, class: "navbar-wagon-item navbar-wagon-button btn" %>

  <% else %>
    <%= link_to "Connexion", new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Inscription", new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
  <% end %>

  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>